pipeline {
    agent any
    environment {
        USERDOCKERHUB = "madson7"
        DIR = "java/webapp/app"
        APP = "webapp"
    }
    parameters {
        choice(name: "ENVIRONMENT",
            choices: ["DEVELOPMENT" , "HOMOLOGATION", "PRODUCTION"],
            description: "Choose the environment for this deployment")
    }
    stages {
        stage('Clone Repository the repository') {
            steps {
                git branch: "main", url: "https://github.com/madson7/dev.git"
            }
        }
        stage ('UNIT testing') {
            steps {
                dir ("${WORKSPACE}/$DIR") {
                    script{
                        sh 'mvn test'
                    }
                }
            }
        }
        stage ('Integration testing') {
            steps {
                dir ("${WORKSPACE}/$DIR") {
                    script{
                        sh 'mvn verify -DskipUnitTests'
                    }
                }
            }
        }
        stage ('Application build with maven in docker') {
            when {
                expression { params.ENVIRONMENT == "DEVELOPMENT" || params.ENVIRONMENT == "HOMOLOGATION" || params.ENVIRONMENT == "PRODUCTION" }
            }
            steps{
                dir ("${WORKSPACE}/$DIR") {
                    script{
                        dockerapp = docker.build("madson7/$APP:${env.BUILD_ID}", "-f ../Dockerfile ..")
                    }
                }
            }
        }
        stage ('Deploy to development environments') {
            when {
                expression { params.ENVIRONMENT == "DEVELOPMENT" }
            }
            steps {
                // sh 'docker rm --force $(docker ps -a -q)'
                sh 'docker run -d -p 8081:8080 madson7/$APP:latest'
            }
        }
        stage ('Push image') {
            when {
                expression { params.ENVIRONMENT == "HOMOLOGATION" || params.ENVIRONMENT == "PRODUCTION" }
            }
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com", "dockerhub") {
                        dockerapp.push("latest")
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
        stage ('Deploy to homologation environments') {
            when {
                expression { params.ENVIRONMENT == "HOMOLOGATION" }
            }
            steps {
                sh 'docker run -d -p 8081:8080 madson7/$APP:latest'
            }
        }
        stage ('Deploy to production environment') {
            when {
                expression { params.ENVIRONMENT == 'PRODUCTION' }
            }
            steps {
                input message: 'Confirm deployment to production...', ok: 'Deploy'
                dir ("${WORKSPACE}/$DIR") {
                    withKubeConfig([credentialsId: 'kubeconfig-prod']) {
                        sh 'kubectl create namespace $APP-production'
                        sh 'sed -i "s|{{image}}|madson7/$APP:latest|g" ../deployment.yaml'
                        sh 'sed -i "s/{{ns}}/$APP-production/g" ../deployment.yaml'
                        sh 'kubectl apply -f ../deployment.yaml'
                    }
                }
            }
        }
    }
}
